### PR TITLE
Update `flight-chrome`, adding cookie banner.

### PR DESCRIPTION
**Pull request by jamesremuscat**
As title.

Trello: https://trello.com/c/smR8nW1M/297-add-cookie-banner

### CODE REVIEW

**Comment by bobwhitelock** [comment]
I tried deleting my cookies and reloading the page and nothing showed - is there something else I need to do to show this?

**Comment by jamesremuscat** [comment]
Clear your cache (or use Chrome's network tools to disable it).

Because we get rid of the hash in the filename of the main script, it stays around longer than we'd like it to.

**Comment by bobwhitelock** [comment]
Thanks, looks great after doing that. One question: does it matter that the same will happen to anyone who has previously visited the site (and so they'll never be shown our cookie warning)?

**Comment by jamesremuscat** [comment]
@bobwhitelock I imagine they'll probably see it "eventually", when their browser decides to check for a newer version.

I'm not sure why it was decided to strip the hash from the script filename originally, but we might want to revisit that decision.

**Comment by bobwhitelock** [comment]
As discussed IRL, looks good and we should fix that at some point

**Pull request merged**
