### PR TITLE
Update text in CR proposed email

### LINKED ISSUE #487: Change to text in "CR proposed" email
Currently it says:

"The change request for this case has been proposed and is awaiting customer authorisation."

As the email is primarily targeted at the customer, I think it would be friendlier to say:

"A change request for this case has been proposed and is awaiting your authorisation."

### PR DESCRIPTION
**Pull request by Atul9**
closes #487

### CODE REVIEW

**Comment by mjtko** [comment]
Hi @Atul9,

Thanks for your contribution. Could you sign our [Contributor License Agreement](https://www.clahub.com/agreements/alces-software/alces-flight-center) please? Once that's out of the way we can take a look at merging your feature into our development branch for inclusion in the next release!

**Comment by Atul9** [comment]
@mjtko done, I have signed the CLA.

**Comment by jamesremuscat** [comment]
@mjtko Are you happy that this will use "your" in all scenarios, including the case history feed and our internal Slack notifications?

**Comment by mjtko** [comment]
Ah, good catch.

The "The" to "A" change should stand in all places where it's required -- but only for the "propose" action.

It should say "your" in the email but "customer" in the card on the feed (and, less importanly Slack).

**Comment by Atul9** [comment]
@mjtko I checked the flow the text is used in mailer, card and slack notifier, the change in decorator text gets reflected everywhere. Can you please suggest where to update/change for -- `It should say "your" in the email but "customer" in the card on the feed (and, less importanly Slack)`

**Comment by mjtko** [comment]
@Atul9: can't suggest a simple place for an update, cos it doesn't exist yet! :smile:

Unfortunately, updating the `text_for_update` method alone is insufficient to fix the issue, cos the system needs to use a different value depending on the context it's called from.

**Comment by mjtko** [comment]
@Atul9: thanks again for your contribution.  I'm closing this now as the resolution of #487 will require a few more changes than included in this PR.

**Pull request closed without merging**
