### PR TITLE
Prevent commenting on cases with pending changes

### PR DESCRIPTION
**Pull request by benarmston**
If a case has pending changes, we no longer show the comment form to admin users.  This prevents the admin from carefully crafting a comment only to have it rejected due to the pending changes.

The presence of pending changes does not affect whether site contacts can add a comment.

I think `Case#allowed_to_comment?` is the correct location to add this rule. Or perhaps it should be `CasePolicy` or `CaseCommenting`?  To be honest I'm a little confused about where such business rules should live.  I'd appreciate some advice on this.

### CODE REVIEW

**Comment by benarmston** [comment]
Fixes #875

**Comment by jamesremuscat** [comment]
@benarmston I've just taken a look and pushed a commit that hopefully cleans up how we were making the "can they comment" decision (which, you're entirely correct to point out, was confusing before).

Please could you check if it makes sense to you?

**Comment by benarmston** [comment]
@jamesremuscat that change makes things look much more sensible.  Thanks for explaining the separation of concerns between `CasePolicy` and `CaseCommenting`.

I can work with that separation of concerns, though I don't understand why we don't want to have the `*Policy` classes deal with the specific case (errr..., I mean deal with whether this specific case can be acted upon by this specific user).  What do we gain by doing things this way?

If you've got time to elaborate I'd like to hear it.

**Comment by benarmston** [comment]
We have conflicts now. I'll rebase and fix.

**Comment by jamesremuscat** [comment]
The `CaseCommenting` class (I think) predates our use of Pundit for permissions. Most of the "can-I-comment" logic was there already so the most straightforward way of tidying up was to put it all there.

It would probably make some sense to merge `CaseCommenting` into `CasePolicy` at some point, but that would be slightly more involved than the small change I made!

**Pull request merged**
