### PR TITLE
Assorted changes as requested by bob

### PR DESCRIPTION
**Pull request by WilliamMcCumstie**
This PR contains most requested fixes from the previous PRs. There are still a few changes to be made which will be based of this branch.

I have rebased on `develop` so the commit numbers have changed.

Please refer to the individual commits for the changes. A lot of them are small changes that are renaming variables.

### CODE REVIEW

**Comment by WilliamMcCumstie** [comment]
:sob: I'm sure I fetched the latest version of the branch

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie don't worry I have recently merged things into `develop` so that may be the issue - I'll rebase this again when I come to look at it.

**Comment by bobwhitelock** [comment]
Rebased on latest `develop`

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie Looks good, thanks for addressing my various comments on the other PRs.

The only things still to look at related to your other PRs are a couple of new comments I've made, https://github.com/alces-software/alces-flight-center/pull/38#discussion_r166284997 and https://github.com/alces-software/alces-flight-center/pull/38#discussion_r166285867. And then there's also some comments I made on https://github.com/alces-software/alces-flight-center/pull/49 you could look at, which I only looked at yesterday.

Once the above have been looked at and you've finished the data migration then we should be close to ready to release all this I believe (unless there's anything else which still needs doing?).

**Comment by bobwhitelock** [comment]
One other thing: not a big deal but if you put the reference when you fix an issue mentioned in a PR comment from the new commit message back to the comment, rather than the other way round in a new comment, then it will have the advantage of not breaking the link as you rebase the new commits, and also means the reason for making the change will be easily viewable in `git log` in future.

**Pull request merged**
